/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hector Garbisu
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelControl = new javax.swing.JPanel();
        PanelVela = new javax.swing.JPanel();
        SliderVela = new javax.swing.JSlider();
        PanelTimon = new javax.swing.JPanel();
        SliderTimon = new javax.swing.JSlider();
        PanelDibujo = new javax.swing.JPanel();
        panelGrafico1 = new PanelGrafico();
        Autor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BarquitoVelero");
        setIconImage(new javax.swing.ImageIcon("src/barquitologo.png").getImage());

        PanelControl.setBorder(javax.swing.BorderFactory.createTitledBorder("Control"));

        PanelVela.setBorder(javax.swing.BorderFactory.createTitledBorder("Orientación Vela"));

        SliderVela.setMaximum(90);
        SliderVela.setMinimum(-90);
        SliderVela.setToolTipText("Orientación de la Vela");
        SliderVela.setValue(0);
        SliderVela.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderVelaStateChanged(evt);
            }
        });
        SliderVela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SliderVelaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SliderVelaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelVelaLayout = new javax.swing.GroupLayout(PanelVela);
        PanelVela.setLayout(PanelVelaLayout);
        PanelVelaLayout.setHorizontalGroup(
            PanelVelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SliderVela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        PanelVelaLayout.setVerticalGroup(
            PanelVelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVelaLayout.createSequentialGroup()
                .addComponent(SliderVela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        PanelTimon.setBorder(javax.swing.BorderFactory.createTitledBorder("Orientación Timón"));

        SliderTimon.setMaximum(90);
        SliderTimon.setMinimum(-90);
        SliderTimon.setToolTipText("Orientación del timón");
        SliderTimon.setValue(0);
        SliderTimon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderTimonStateChanged(evt);
            }
        });
        SliderTimon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SliderTimonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SliderTimonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelTimonLayout = new javax.swing.GroupLayout(PanelTimon);
        PanelTimon.setLayout(PanelTimonLayout);
        PanelTimonLayout.setHorizontalGroup(
            PanelTimonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SliderTimon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelTimonLayout.setVerticalGroup(
            PanelTimonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTimonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SliderTimon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelControlLayout = new javax.swing.GroupLayout(PanelControl);
        PanelControl.setLayout(PanelControlLayout);
        PanelControlLayout.setHorizontalGroup(
            PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelVela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTimon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PanelControlLayout.setVerticalGroup(
            PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelVela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTimon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelDibujo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelGrafico1.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout panelGrafico1Layout = new javax.swing.GroupLayout(panelGrafico1);
        panelGrafico1.setLayout(panelGrafico1Layout);
        panelGrafico1Layout.setHorizontalGroup(
            panelGrafico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        panelGrafico1Layout.setVerticalGroup(
            panelGrafico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelDibujoLayout = new javax.swing.GroupLayout(PanelDibujo);
        PanelDibujo.setLayout(PanelDibujoLayout);
        PanelDibujoLayout.setHorizontalGroup(
            PanelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGrafico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelDibujoLayout.setVerticalGroup(
            PanelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGrafico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Autor.setText("Héctor Garbisu DIU 2015");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Autor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                        .addComponent(Autor)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SliderVelaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderVelaStateChanged
        panelGrafico1.anguloVela = SliderVela.getValue()*Math.PI/180.0;
        panelGrafico1.repaint();
    }//GEN-LAST:event_SliderVelaStateChanged

    private void SliderVelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliderVelaMouseEntered
        panelGrafico1.focusVela = true;
        panelGrafico1.repaint();
    }//GEN-LAST:event_SliderVelaMouseEntered

    private void SliderVelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliderVelaMouseExited
        panelGrafico1.focusVela = false;
        panelGrafico1.repaint();
    }//GEN-LAST:event_SliderVelaMouseExited

    private void SliderTimonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderTimonStateChanged
        // TODO add your handling code here:
        panelGrafico1.anguloTimon = SliderTimon.getValue()*Math.PI/180.0;        
        panelGrafico1.repaint();
    }//GEN-LAST:event_SliderTimonStateChanged

    private void SliderTimonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliderTimonMouseEntered
        panelGrafico1.focusTimon = true;
        panelGrafico1.repaint();        
    }//GEN-LAST:event_SliderTimonMouseEntered

    private void SliderTimonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliderTimonMouseExited
        panelGrafico1.focusTimon = false;
        panelGrafico1.repaint();        
    }//GEN-LAST:event_SliderTimonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autor;
    private javax.swing.JPanel PanelControl;
    private javax.swing.JPanel PanelDibujo;
    private javax.swing.JPanel PanelTimon;
    private javax.swing.JPanel PanelVela;
    private javax.swing.JSlider SliderTimon;
    private javax.swing.JSlider SliderVela;
    private PanelGrafico panelGrafico1;
    // End of variables declaration//GEN-END:variables
}
